name: CivChat2
main: vg.civcraft.mc.civchat2.CivChat2
version: 1.0.3
author: jjj5311
depend: [NameLayer, CivModCore]
softdepend: [Mercury]
commands:
    tell:
      aliases: [message, msg, m, pm]
    afk:
    reply:
      aliases: [r]
    ignore:
      aliases: [i]
    ignoregroup:
      aliases: [ig, igroup, ignoreg]
    groupc:
      aliases: [groupchat, gchat, gc, g]
    ignorelist:
    exit:
      aliases: [e]
    say:
